usb_camera_node_dvpp:
  ros__parameters:
    # 摄像头设备路径
    device_path: "/dev/video0"
    
    # 图像分辨率
    width: 1920
    height: 1080
    
    # 帧率
    fps: 30
    
    # 压缩图像发布设置
    publish_compressed: true
    
    # DVPP硬件加速参数
    enable_dvpp: true                       # 启用DVPP硬件加速
    enable_hardware_resize: false           # 是否启用硬件缩放
    resize_width: 1920                      # 缩放后的宽度
    resize_height: 1080                     # 缩放后的高度
