usb_camera_node_dvpp:
  ros__parameters:
    # 摄像头设备路径
    device_path: "/dev/video0"
    
    # 图像分辨率
    width: 1920
    height: 1080
    
    # 帧率
    fps: 30
    
    # 像素格式 (mjpeg 或 yuyv)
    pixel_format: "mjpeg"
    
    # DVPP硬件加速参数
    enable_dvpp: true                       # 启用DVPP硬件加速
    dvpp_output_format: "yuv420sp"          # DVPP输出格式
    enable_hardware_resize: false           # 是否启用硬件缩放
    resize_width: 1920                      # 缩放后的宽度
    resize_height: 1080                     # 缩放后的高度
