usb_camera_node:
  ros__parameters:
    # 摄像头设备路径
    device_path: "/dev/video0"
    
    # 图像分辨率
    width: 1920
    height: 1080
    
    # 帧率
    fps: 30
    
    # 压缩图像发布设置
    publish_compressed: true