usb_camera_node:
  ros__parameters:
    # 摄像头设备路径
    device_path: "/dev/video0"
    
    # 图像分辨率
    width: 1920
    height: 1080
    
    # 帧率
    fps: 30
    
    # 像素格式 (mjpeg 或 yuyv)
    pixel_format: "mjpeg"
    
    # 压缩图像发布
    publish_compressed: true
    jpeg_quality: 60