world:
  host: "127.0.0.1"
  port: 2000
  sync_mode: false
  fixed_delta_seconds: 0.0333333333
  town: ""

vehicles:
  - id: ego
    blueprint: vehicle.tesla.model3
    spawn_point_index: 0
    autopilot: false
    front_camera:
      width: 1280
      height: 720
      fov: 90.0
      fps: 30
      quality: 50
      frame_id: camera_front


